spec: 1
services:
  - type: web
    name: roulette-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://admin:aLqNou9NGyaVk0g8roYnBsmPXDSiLz9R@dpg-d1ftqqali9vc739vuieg-a.oregon-postgres.com/roulette_jnfa
      - key: FRONTEND_URL
        value: https://frontend-f4rf.onrender.com # Обновлено на ваш URL фронтенда
  - type: static
    name: roulette-frontend
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend-bse2.onrender.com # Обновлено на ваш URL бэкенда
